services:
  web:
    build:
      dockerfile: deployments/containers/Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      POSTGRES_DBNAME: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      db:
        condition: service_started
        restart: true

  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_PASSWORD: example