FROM    python:3.11.4

WORKDIR '/app'
COPY    requirements_base.txt .
COPY    requirements_dev.txt .


RUN     python -m pip install -r requirements_dev.txt

COPY     . .

CMD     ["python", "manage.py", "runserver", "0.0.0.0:8000"]