name: Action on push
run-name: Push from ${{ github.actor }}
on: [push, pull_request]
jobs:
  Super-Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: super-linter/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          VALIDATE_LANGUAGES: "!black"
